module.exports = [
"Timestamp",
"How many active accounts do you have?",
"How many characters do you have in BRAVE?",
"Where do you call home?",
"How many BRAVE groups and/or communities do you participate in?",
"I have characters in...",
"What time is the beginning of your preferred playtime? (UTC/EVE time)",
"On which days?",
"How many hours do you play each week?",
"How often do you find something to do when you log in?",
"Are you interested in living in Nullsec?",
"What activity are you MOST interested in?",
"Which of the following income activities do you regularly participate in?",
"How much ISK do you make on average in ONE HOUR through ACTIVE income sources?",
"How often do you actively farm ISK? ",
"How much ISK do you earn IN ONE WEEK, through PASSIVE income sources?",
"Have you ever sold a PLEX for ISK to support your wallet?",
"My primary source of income is...",
"How would you rate BRAVE's support for your style of income?",
"Where do you go to make ISK?",
"I tend to make ISK...",
"I make money on my own because...",
"Are your groups filled with other BRAVE members?",
"How many people do you usually fly with when you're looking to make isk?",
"How do you find groups in BRAVE?",
"What advice would you give to someone looking to find groups in BRAVE?",
"Jita is...",
"Utopia is...",
"Poitot is...",
"Polaris is...",
"I would like to get involved with the following, but I don't know how:",
"Have you ever sold items to a BRAVE buyback program?",
"Are there any gaps in our buyback programs that you would like to see filled?",
"How many researched blueprint originals (BPO's) do you own?",
"Have you ever built a Capital ship of any kind?",
"How effective is BRAVE's Industry division? ",
"Is Motre a c***?",
"How much of a c*** is Motre?",
"I enjoy...",
"How much ISK have you received from BRAVE's SRP (Ship Replacement Program?)",
"Can I bring my drake?",
"Rate the skill of our PVP team.",
"Rate the direction and focus of our PVP team.",
"What roles do our doctrines fail to fill?",
"What capital ships can you fly?",
"How effective is BRAVE's PVP division? ",
"I regularly find information about BRAVE's current events through the following:",
"The BEST way to store BRAVE's information for people to reference is",
"How often do you have trouble finding BRAVE information?",
"Did you know there was a complaint form that goes to HR?",
"Did you know sending unapproved Corp or Alliance mail is a kickable offense?",
"How satisfied are you with BRAVE's internal communications?",
"How would you improve BRAVE's internal communications?",
"Have you ever watched a Youtube video featuring BRAVE?",
"Explain 7o",
"How satisfied are you with BRAVE's external communications?",
"Have you ever asked a question in Brave Dojo?",
"Have you ever answered a question in Brave Dojo?",
"Does your overview tell you that a suspect/criminal/outlaw BRAVE member, or blue pilot, is actually friendly?",
"Which activities would you like to see more classes for?",
"How did you find BRAVE Collective?",
"How effective is BRAVE's Recruitment/Education division?",
"How well are complaints resolved?",
"How often does HR get in the way of your fun?",
"How sexy is Markonius Porkbutte?",
"How effective is BRAVE's HR division?",
"Any suggestions or comments for HR?",
"Asset Management's primary roles include:",
"How reasonable are Jump Freighter hauling rates?",
"How reasonable are Blockade Runner hauling rates?",
"How reasonable are Highsec hauling rates?",
"Rate the speed at which contracts are completed",
"Any suggestions or comments for Asset Management?",
"How effective is BRAVE's Asset Management division?",
"Do you know what the CNM does?",
"Do you feel that the CNM represents you?",
"Have you ever read any CNM Minutes?",
"Name a CNM member off the top of your head",
"Representative Feedback",
"Election Feedback",
"How effective is BRAVE's Council of Newbie Management?",
"Have you connected to BRAVE's Mumble server?",
"Have you connected to BRAVE's Jabber server?",
"Which of the following tools would you most like to see?",
"How satisfied are you with BRAVE's Core Auth system?",
"Did you experience problems signing up for Core or connecting to Mumble?",
"What documentation would you like to see from BRAVE IT?",
"How effective is BRAVE IT?",
"Are you a spai?",
"Would you like to be contacted regarding any of your responses?",
"Do you have any final comments?",
]
